services:
  - type: web
    name: lepakshi-spices-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://lepakshi-spices-user.vercel.app
      - key: ADMIN_FRONTEND_URL
        value: https://lepakshi-spices-admin.vercel.app
