import { Router } from 'express';
import { authenticate, requireRole } from '../middleware/auth.middleware.js';
import healthRoute from './health.route.js';
import categoriesRoute from './category.route.js';
import productsRoute from './product.route.js';
import authRoute from './auth.route.js';
import uploadRoute from './upload.route.js';
import genericRoute from './generic.route.js';
import ordersRoute from './order.route.js';
import adminOrdersRoute from './admin-order.route.js';
import cartRoute, { wishlistRouter } from './cart.route.js';
import addressesRoute from './address.route.js';
import collectionRoute from './collection.route.js';
import { couponAdminRouter, couponPublicRouter } from './coupon.route.js';
import { campaignAdminRouter, campaignPublicRouter } from './campaign.route.js';
import { recipeAdminRouter, recipePublicRouter } from './recipe.route.js';
import { productReviewRouter, publicReviewRouter, adminReviewRouter } from './review.route.js';
import { settingsAdminRouter, settingsPublicRouter } from './settings.route.js';
import { wholesaleAdminRouter, wholesalePublicRouter, wholesaleQuotePublicRouter, wholesaleQuoteCustomerRouter } from './wholesale.route.js';
import packagingRoute from './packaging.route.js';
import adminCustomerRoute from './admin-customer.route.js';
import auditRoute from './audit.route.js';
import { getDashboardStatsController } from '../controllers/dashboard.controller.js';
import { asyncHandler } from '../middleware/async-handler.js';
import locationRoute from './location.route.js';
import realtimeRoute from './realtime.route.js';
import launchRoute from './launch.route.js';

const router = Router();
router.use('/health', healthRoute);
router.use('/realtime', realtimeRoute);
router.use('/launch', launchRoute);
router.use('/admin/launch', launchRoute);
router.use('/auth', authRoute);
router.use('/categories', categoriesRoute);
router.use('/products', productsRoute);
router.use('/products/:id/reviews', productReviewRouter);
router.use('/reviews', publicReviewRouter);
router.use('/orders', ordersRoute);
router.use('/admin/orders', authenticate, requireRole('admin', 'staff', 'manager'), adminOrdersRoute);
router.use('/cart', authenticate, cartRoute);
router.use('/wishlist', authenticate, wishlistRouter);
router.use('/addresses', authenticate, addressesRoute);
router.use('/location', locationRoute);
router.use('/upload', authenticate, requireRole('admin', 'staff', 'manager'), uploadRoute);

router.use('/collections', collectionRoute);
router.use('/admin/coupons', authenticate, requireRole('admin', 'staff', 'manager'), couponAdminRouter);
router.use('/coupons', couponPublicRouter);
router.use('/admin/campaigns', authenticate, requireRole('admin', 'staff', 'manager'), campaignAdminRouter);
router.use('/campaigns', campaignPublicRouter);
router.use('/admin/recipes', authenticate, requireRole('admin', 'staff', 'manager'), recipeAdminRouter);
router.use('/recipes', recipePublicRouter);
router.use('/admin/reviews', authenticate, requireRole('admin', 'staff', 'manager'), adminReviewRouter);
router.use('/admin/settings', authenticate, requireRole('admin', 'staff', 'manager'), settingsAdminRouter);
router.use('/admin/customers', authenticate, requireRole('admin', 'staff', 'manager'), adminCustomerRoute);
router.use('/admin/audit-logs', authenticate, requireRole('admin', 'staff', 'manager'), auditRoute);
router.get('/admin/dashboard/stats', authenticate, requireRole('admin', 'staff', 'manager'), asyncHandler(getDashboardStatsController));
router.use('/admin', authenticate, requireRole('admin', 'staff', 'manager'), wholesaleAdminRouter);
router.use('/settings', settingsPublicRouter);
router.use('/wholesale-inquiries', wholesalePublicRouter);
router.use('/wholesale/quotes', wholesaleQuoteCustomerRouter);
router.use('/wholesale/quotes', wholesaleQuotePublicRouter);
router.use('/', packagingRoute);

router.use('/entities', authenticate, requireRole('admin'), genericRoute);

export default router;

