CREATE TABLE IF NOT EXISTS `launch_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_enabled` BOOLEAN NOT NULL DEFAULT TRUE,
  `has_launched` BOOLEAN NOT NULL DEFAULT FALSE,
  `launched_at` DATETIME NULL,
  `launched_by` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
